test:
  config:
    name: "jeffrey-prod"
task:
  cron: "1 * * * * ?"
spring:
  security:
    user:
      name: jeffrey
      password: 123456
  data:
    mongodb:
      database: runboot
      host: 192.168.95.10
      port: 27017
management:
#  server:
#    port: 9030
  endpoints:
    web:
      exposure:
        include: '*'  # 包含端点，可以访问；多端点之间用逗号分隔
  endpoint:
    health:
      show-details: always
zookeeper:
  address: 127.0.0.1:2181
  timeout: 4000
accessToken:
  validity:
    timeout: 7200
refreshToken:
  validity:
    timeout: 86400
